server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users_management_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma PowerUp FoodCourt Hexagonal Microservices"
appVersion: "1.0.0"

jwt:
  expiration: 840000000
